# Generated by Django 5.1 on 2024-08-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(default=0)),
                ('value', models.FloatField(default=0)),
                ('issue_date', models.CharField(max_length=10)),
                ('parts_seller_name', models.CharField(max_length=30)),
                ('parts_buyer_name', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
            ],
        ),
    ]
